name: doan
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - run: yarn run build
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 103.101.162.46 #hostname of server
          username: root #username login to server
          password: Fo0GbbOQlOAnbpv #password login to server
          port: 22 #port of server - often port is 22
          script: | # run with multiple script
            cd /var/www/vnsupplements/back_end
            git checkout .
            git pull
            yarn
            yarn build
            pm2 start ecosystem-dev.json
